{
  imports = [
    ../options.nix
    ./audio.nix
    ./battery.nix
    ./bluetooth.nix
    ./boot.nix
    ./ca-certificates.nix
    ./cifs.nix
    ./display-manager.nix
    ./dns.nix
    ./file.nix
    ./fwupd.nix
    ./game.nix
    ./gpu-screen-recorder.nix
    ./internationalization.nix
    ./lix.nix
    ./logind.nix
    ./network.nix
    ./nix-ld.nix
    ./nixsettings.nix
    ./nvidia.nix
    ./printer.nix
    ./security.nix
    ./solaar.nix
    ./ssh.nix
    ./usbguard.nix
    ./user.nix
    ./video.nix
    ./virtualization.nix
    ./vpn.nix
  ];
}
