{
  imports = [
    ./audio.nix
    ./bluetooth.nix
    ./boot.nix
    ./ca-certificates.nix
    ./dns.nix
    ./file.nix
    ./fwupd.nix
    ./gpg.nix
    ./internationalization.nix
    ./logind.nix
    ./network.nix
    ./nixsettings.nix
    ./printer.nix
    ./security.nix
    ./ssh.nix
    ./user.nix
    ./virtualisation.nix
  ];
}
