{
  imports = [
    ./audio.nix
    ./bluetooth.nix
    ./boot.nix
    ./ca-certificates.nix
    ./dns.nix
    ./dm.nix
    ./gpg.nix
    ./internationalization.nix
    ./network.nix
    ./nixsettings.nix
    ./video.nix
    ./printer.nix
    ./security.nix
    ./ssh.nix
    ./user.nix
  ];
}