---
name: Dead code analysis

on: [push, pull_request]

jobs:
  deadnix:
    name: Deadnix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - uses: cachix/cachix-action@v15
        with:
          name: deadnix
      - name: Run deadnix
        uses: astro/deadnix-action@main
        with:
          flags: "--exclude **/hardware-configuration.nix ./flake.nix"
