---
name: Lint nix config

on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - name: Run flake check
        run: nix flake check
      - name: Run nix fmt
        run: nix fmt
      - name: Run flake check
        run: nix flake check
